version: "3.7"
services:
  web:
    image: nginx
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./host.key:/etc/nginx/certs/serika_playfab.key
      - ./host.cert:/etc/nginx/certs/serika_playfab.cert
      - ./nginx.server.conf:/etc/nginx/conf.d/serika.playfab.conf

