version: "3.7"
services:
  gateway:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
      - "23456:23456"
    volumes:
      - ../gateway/host.key:/etc/nginx/certs/serika_playfab.key
      - ../gateway/host.cert:/etc/nginx/certs/serika_playfab.cert
      - ../gateway/nginx.server.conf:/etc/nginx/conf.d/serika.playfab.conf

  login-server:
    image: nginx
    volumes:
      - ../login_server/index.html:/usr/share/nginx/html/index.html
      - ../login_server/nginx.server.conf:/etc/nginx/conf.d/serika.playfab.conf

  external-server:
    image: external-server
    build:
      context: ../
      dockerfile: scripts/external_server.dockerfile
    ports:
      - "23456:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: wisdom
    ports:
      - "5432:5432"
    volumes:
      - .:/tmp


#  test-client:
#    image: test-client
#    build:
#      context: ../
#      dockerfile: scripts/test_client.dockerfile
#    depends_on:
#      - external-server